CREATE TABLE KH_STUDENT(
	STD_NO NUMBER PRIMARY KEY,
    STD_NAME NVARCHAR2(5) NOT NULL,
    STD_AGE NUMBER NOT NULL,
    MAJOR NVARCHAR2(10) NOT NULL,
    ENT_DATE DATE DEFAULT SYSDATE
);

SELECT * FROM KH_STUDENT;

CREATE SEQUENCE SQE_STUDENT
START WITH 1
INCREMENT BY 1
NOMAXVALUE 
NOMINVALUE
NOCYCLE
NOCACHE;



INSERT INTO KH_STUDENT
VALUES(SQE_STUDENT.NEXTVAL,'짱구',15,'경영학과',SYSDATE);
INSERT INTO KH_STUDENT
VALUES(SQE_STUDENT.NEXTVAL,'훈이',15,'컴퓨터공학과',SYSDATE);
INSERT INTO KH_STUDENT
VALUES(SQE_STUDENT.NEXTVAL,'유리',15,'호텔관광학과',SYSDATE);
INSERT INTO KH_STUDENT
VALUES(SQE_STUDENT.NEXTVAL,'철수',19,'사회복지학과',DEFAULT);


ROLLBACK;

DROP TABLE KH_STUDENT;

SELECT STD_NO,STD_NAME,STD_AGE,MAJOR,
TO_CHAR(ENT_DATE,'YYYY"년" MM"월" DD"일"')
FROM KH_STUDENT;

UPDATE 

DELETE 