-- 1번
SELECT * FROM TB_PROFESSOR;
SELECT PROFESSOR_NAME,PROFESSOR_SSN 
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3;
-- 2번
SELECT PROFESSOR_NAME 교수이름,PROFESSOR_SSN 나이,
DECODE(SUBSTR(PROFESSOR_SSN,8,1),'1','남')
FROM TB_PROFESSOR
WHERE 
ORDER BY PROFESSOR_SSN; 
-- 3번

-- 4번
SELECT TO_CHAR(TO_DATE(991011,'YY/MM/DD'),'YYYY/MM/DD') "첫 번째" ,
TO_CHAR(TO_DATE(491011,'YY/MM/DD'),'YYYY/MM/DD')"두 번째" ,
TO_CHAR(TO_DATE(991011,'RR/MM/DD'),'RRRR/MM/DD')  "세 번째",
TO_CHAR(TO_DATE(491011,'RR/MM/DD'),'RRRR/MM/DD') "네 번째" FROM DUAL;
--5번
SELECT * FROM TB_STUDENT; 
SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_PROFESSOR tp; 
SELECT STUDENT_NO,STUDENT_NAME,DEPARTMENT_NO 
FROM TB_STUDENT
UNION
SELECT DEPARTMENT_NO,DEPARTMENT_NAME,DEPARTMENT_NO
FROM TB_DEPARTMENT;

--------------------------------------------------------------------
SELECT DEPARTMENT_NAME "학과 명",CATEGORY 계열
FROM TB_DEPARTMENT;

SELECT DEPARTMENT_NAME "학과 명",CAPACITY 정원
FROM TB_DEPARTMENT;

SELECT DEPARTMENT_NAME FROM TB_DEPARTMENT;
SELECT STUDENT_NAME,STUDENT_SSN,
DECODE(STUDENT_SSN,'2','여')
FROM TB_STUDENT
WHERE  ABSENCE_YN ='N';

SELECT  DEPARTMENT_NAME , CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

SELECT CATEGORY 
FROM TB_DEPARTMENT
GROUP BY CATEGORY 
ORDER BY CATEGORY ;

SELECT STUDENT_NO,STUDENT_NAME,STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y';

