-- 1.
SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS 주소지
FROM TB_STUDENT
ORDER BY 1;
-- 2.
SELECT STUDENT_NAME, STUDENT_SSN 
FROM TB_STUDENT ts 
WHERE ABSENCE_YN = 'Y'
ORDER BY 2 DESC;
-- 3.
SELECT STUDENT_NAME 학생이름, STUDENT_NO 학번,STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT ts 
WHERE STUDENT_NO LIKE '9%'
AND STUDENT_ADDRESS LIKE '경기도%'
OR STUDENT_ADDRESS LIKE '강원도%'
ORDER BY 1;
-- 4.
SELECT PROFESSOR_NAME,PROFESSOR_SSN
FROM TB_PROFESSOR
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '법학과'
ORDER BY 2;
-- 5.
SELECT STUDENT_NO,TO_CHAR(POINT,'FM9.00')
FROM TB_STUDENT ts 
JOIN TB_GRADE tg USING(STUDENT_NO)
WHERE TERM_NO = '200402'
AND CLASS_NO = 'C3118100'
ORDER BY 2 DESC , STUDENT_NO;

-- 6. 
SELECT STUDENT_NO,STUDENT_NAME,DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
ORDER BY STUDENT_NAME;
-- 7.
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO);
-- 8.
-- 9. 
-- 13. 
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS 
LEFT JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE CATEGORY = '예체능'
AND PROFESSOR_NO IS NULL;

-- 14.
SELECT STUDENT_NAME 학생이름, NVL(PROFESSOR_NAME, '지도교수 미지정') 지도교수
FROM TB_STUDENT S
LEFT JOIN TB_PROFESSOR P ON(COACH_PROFESSOR_NO = PROFESSOR_NO)
JOIN TB_DEPARTMENT D ON(S.DEPARTMENT_NO = D.DEPARTMENT_NO) 
-- STUDENT,PROFESSOR,DEPARTMENT 세 개 다 DEPARTMENT_NO 라는 컬럼명을 가지고 있어서
-- 어떤 테이블에서 컬럼명을 가져오는지 명칭을 정확하게 해줘야한다.                                                     
WHERE DEPARTMENT_NAME = '서반아어학과'
ORDER BY STUDENT_NO;

-- 15. 
SELECT STUDENT_NO 학번,STUDENT_NAME 이름,DEPARTMENT_NAME "학과 이름",AVG(POINT) 평점
FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(STUDENT_NO)
WHERE ABSENCE_YN = 'N'
GROUP BY STUDENT_NO,STUDENT_NAME,DEPARTMENT_NAME
HAVING AVG(POINT) >= 4
ORDER BY STUDENT_NO;

-- 16. 
SELECT CLASS_NO, CLASS_NAME, TRUNC(AVG(POINT),8)
FROM TB_CLASS 
JOIN TB_GRADE USING(CLASS_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '환경조경학과'
AND CLASS_TYPE LIKE '전공%'
GROUP BY CLASS_NO, CLASS_NAME
ORDER BY 1;